import {
  FiActivity,
  FiAirplay,
  FiAperture,
  FiBarChart2,
  FiBook,
  FiBookmark,
  FiBriefcase,
  FiCalendar,
  FiClipboard,
  FiCpu,
  FiFileText,
  FiFolderPlus,
  FiGift,
  FiGrid,
  FiHome,
  FiLayers,
  FiMail,
  FiMap,
  FiMessageSquare,
  FiPackage,
  FiPocket,
  FiRss,
  FiShare2,
  FiShoppingCart,
  FiUsers,
} from "react-icons/fi";
const MENU_ITEMS = [
  {
    key: "overview",
    label: "OVERVIEW",
    isTitle: true,
  },
  {
    key: "apps-calendar",
    label: "Calendar",
    isTitle: false,
    icon: FiCalendar,
    url: "/apps/calendar",
  },
  {
    key: "apps-chat",
    label: "Chat",
    isTitle: false,
    icon: FiMessageSquare,
    url: "/apps/chat",
  },
  {
    key: "apps-ecommerce",
    label: "Ecommerce",
    isTitle: false,
    icon: FiShoppingCart,
    children: [
      {
        key: "ecommerce-dashboard",
        label: "Dashboard",
        url: "/apps/ecommerce/dashboard",
        parentKey: "apps-ecommerce",
      },
      {
        key: "ecommerce-products",
        label: "Products",
        url: "/apps/ecommerce/products",
        parentKey: "apps-ecommerce",
      },
      {
        key: "ecommerce-details",
        label: "Product Details",
        url: "/apps/ecommerce/product-details",
        parentKey: "apps-ecommerce",
      },
      {
        key: "ecommerce-edit-product",
        label: "Add Product",
        url: "/apps/ecommerce/edit-product",
        parentKey: "apps-ecommerce",
      },
      {
        key: "ecommerce-customers",
        label: "Customers",
        url: "/apps/ecommerce/customers",
        parentKey: "apps-ecommerce",
      },
      {
        key: "ecommerce-orders",
        label: "Orders",
        url: "/apps/ecommerce/orders",
        parentKey: "apps-ecommerce",
      },
      {
        key: "ecommerce-order-details",
        label: "Order Details",
        url: "/apps/ecommerce/order/details",
        parentKey: "apps-ecommerce",
      },
      {
        key: "ecommerce-sellers",
        label: "Sellers",
        url: "/apps/ecommerce/sellers",
        parentKey: "apps-ecommerce",
      },
      {
        key: "ecommerce-shopping-cart",
        label: "Shopping Cart",
        url: "/apps/ecommerce/shopping-cart",
        parentKey: "apps-ecommerce",
      },
      {
        key: "ecommerce-checkout",
        label: "Checkout",
        url: "/apps/ecommerce/checkout",
        parentKey: "apps-ecommerce",
      },
    ],
  },
  {
    key: "apps-crm",
    label: "CRM",
    isTitle: false,
    icon: FiUsers,
    children: [
      {
        key: "crm-dashboard",
        label: "Dashboard",
        url: "/apps/crm/dashboard",
        parentKey: "apps-crm",
      },
      {
        key: "crm-contacts",
        label: "Contacts",
        url: "/apps/crm/contacts",
        parentKey: "apps-crm",
      },
      {
        key: "crm-opportunities",
        label: "Opportunities",
        url: "/apps/crm/opportunities",
        parentKey: "apps-crm",
      },
      {
        key: "crm-leads",
        label: "Leads",
        url: "/apps/crm/leads",
        parentKey: "apps-crm",
      },
      {
        key: "crm-customers",
        label: "Customers",
        url: "/apps/crm/customers",
        parentKey: "apps-crm",
      },
    ],
  },
  {
    key: "apps-email",
    label: "Email",
    isTitle: false,
    icon: FiMail,
    children: [
      {
        key: "email-inbox",
        label: "Inbox",
        url: "/apps/email/inbox",
        parentKey: "apps-email",
      },
      {
        key: "email-read-email",
        label: "Read Email",
        url: "/apps/email/details",
        parentKey: "apps-email",
      },
      {
        key: "email-compose-email",
        label: "Compose Email",
        url: "/apps/email/compose",
        parentKey: "apps-email",
      },
    ],
  },
  {
    key: "apps-social",
    label: "Social Feed",
    isTitle: false,
    icon: FiRss,
    url: "/apps/social-feed",
    badge: {
      variant: "pink",
      text: "Hot",
    },
  },
  {
    key: "apps-companies",
    label: "Companies",
    isTitle: false,
    icon: FiActivity,
    url: "/apps/companies",
  },
  {
    key: "apps-projects",
    label: "Projects",
    isTitle: false,
    icon: FiBriefcase,
    children: [
      {
        key: "project-list",
        label: "List",
        url: "/apps/projects/list",
        parentKey: "apps-projects",
      },
      {
        key: "project-details",
        label: "Details",
        url: "/apps/projects/:id/details",
        parentKey: "apps-projects",
      },
      {
        key: "project-create-project",
        label: "Create Project",
        url: "/apps/projects/create",
        parentKey: "apps-projects",
      },
    ],
  },
  {
    key: "apps-tasks",
    label: "Tasks",
    isTitle: false,
    icon: FiClipboard,
    children: [
      {
        key: "task-list",
        label: "List",
        url: "/apps/tasks/list",
        parentKey: "apps-tasks",
      },
      {
        key: "task-details",
        label: "Details",
        url: "/apps/tasks/details",
        parentKey: "apps-tasks",
      },
      {
        key: "task-kanban",
        label: "Kanban Board",
        url: "/apps/tasks/kanban",
        parentKey: "apps-tasks",
      },
    ],
  },
  {
    key: "apps-contacts",
    label: "Contacts",
    isTitle: false,
    icon: FiBook,
    children: [
      {
        key: "contacts-list",
        label: "Members List",
        url: "/apps/contacts/list",
        parentKey: "apps-contacts",
      },
      {
        key: "contacts-profile",
        label: "Profile",
        url: "/apps/contacts/profile",
        parentKey: "apps-contacts",
      },
    ],
  },
  {
    key: "apps-tickets",
    label: "Tickets",
    isTitle: false,
    icon: FiAperture,
    children: [
      {
        key: "tickets-list",
        label: "List",
        url: "/apps/tickets/list",
        parentKey: "apps-tickets",
      },
      {
        key: "tickets-details",
        label: "Details",
        url: "/apps/tickets/details",
        parentKey: "apps-tickets",
      },
    ],
  },
  {
    key: "apps-file-manager",
    label: "File Manager",
    isTitle: false,
    icon: FiFolderPlus,
    url: "/apps/file-manager",
  },
];
export default MENU_ITEMS;
