import "./globals.css";

import "@assets/css/animate.min.css";
import "@assets/css/bootstrap.min.css";
import "@assets/css/flaticon.min.css";
import "@assets/css/fontawesome-5.14.0.min.css";
import "@assets/css/jquery.animatedheadline.css";
import "@assets/css/magnific-popup.min.css";
import "@assets/css/nice-select.min.css";
import "@assets/css/slick.min.css";
import "@assets/css/style.css";

export const metadata = {
  title: "Oxence - Web Design Company React NextJS Template",
  description: "Generated by oxence - Web Design Company React NextJS Template",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
